### ISSUE TITLE
Funktioniert nicht ohne Internetverbindung

### ISSUE THREAD

**Issue by bafto** [gommzystudio/htwg-chess#14]
Wenn dir Tailwind so wichtig ist, dann lad es runter und pack es ins projekt, aber downloaded es nicht jedes mal mit nem `<link>`.
Dein Gui geht nicht ohne Internet.

**Comment by gommzystudio** [comment]
Danke für den Hinweis. Kam nie auf die Idee das Spiel offline auszuführen.
Wird jetzt local geladen.
